version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    command: ["elasticsearch", "-Elogger.level=ERROR"]
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
       "ES_JAVA_OPTS": "-Xms2g -Xmx2g -XX:UseAVX=2"
       "ELASTIC_PASSWORD": elastic
    networks:
      - elk_stack
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      
      
  logstash:
    image: docker.elastic.co/logstash/logstash:8.1.2
    container_name: logstash
    networks:
      - elk_stack
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
       "ES_JAVA_OPTS": "-Xms1g -Xmx1g"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk_stack 
    environment:
       "SERVER_NAME": "0.0.0.0"
       "ELASTICSEARCH_HOSTS": "http://elasticsearch:9200"
      
    volumes:
      - ./kibana/data:/usr/share/kibana/data
 #     - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml


networks:
 elk_stack:
   driver: bridge